# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

languages:
  Python: true
  JavaScript: true
exclude_paths:
  - "src/ggrc/assets/javascripts/generated/*"
  - "src/ggrc/static/mockups/js/lib"
